name: Auto Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 需要写入权限来创建 GitHub Release

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 需要完整的git历史来生成Changelog

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25.x

      - name: Run Goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # 以下是传递给 Goreleaser 的参数
          distribution: goreleaser # 或者 goreleaser-pro 如果你购买了专业版
          version: latest # 使用最新版本的 Goreleaser
          args: release --clean # 运行 release 命令，生成发布文件并推送到 GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Goreleaser 需要这个token来创建Release
